version: '3'

networks:
  default:
    driver: bridge
    
services:

  html:
    image: canfone/html:latest
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    networks:
      - default
    volumes:
      - html-app:/var/www/html
      
  wtsl:
    image: canfone/wordpress:latest
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    networks:
      - default
    volumes:
      - wtsl-app:/var/www/wordpress

  php-fpm:
    image: canfone/php-fpm:latest
    expose:
      - "9000"
    volumes:
      - ${PHP_FPM_CUSTOM_INI_PATH}:/usr/local/etc/php/conf.d/custom.ini
      - html-app:/var/www/html
      - wtsl-app:/var/www/wtsl
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    depends_on:
      - html
      - wtsl
    networks:
      default:
        aliases:
          - "dev.whattokyosolong.com"

  nginx:
    image: canfone/nginx:latest
    volumes:
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
      - html-app:/var/www/html
      - wtsl-app:/var/www/wtsl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm
    networks:
      default:
        aliases:
          - "dev.whattokyosolong.com"
        
  letsencrypt:
    image: certbot/certbot
    volumes:
      - ${LETSENCRYPT_ETC_PATH}:/etc/letsencrypt
      - ${LETSENCRYPT_LIB_PATH}:/var/lib/letsencrypt
      - ${LETSENCRYPT_LOG_PATH}:/var/log/letsencrypt
      - wtsl-app:/data/letsencrypt
    depends_on:
      - nginx
      - wtsl
    
  mysql:
    image: canfone/mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - default

volumes:
    html-app:
    wtsl-app:
    certbot-etc:
    certbot-var:
