version: '3'

networks:
  default:
    driver: bridge

services:

  html:
    image: canfone/html:latest
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    networks:
      - default
    volumes:
      - html-volume:/var/www/html
      
  wtsl:
    image: canfone/wordpress:latest
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    networks:
      - default
    volumes:
      - wtsl-volume:/var/www/wordpress

  php-fpm:
    image: canfone/php-fpm:latest
    expose:
      - "9000"
    volumes:
      - ${PHP_FPM_CUSTOM_INI_PATH}:/usr/local/etc/php/conf.d/custom.ini
      - html-volume:/var/www/html
      - wtsl-volume:/var/www/wtsl
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    depends_on:
      - html
      - wtsl
    networks:
      - default

  nginx:
    image: canfone/nginx:latest
    volumes:
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
      - html-volume:/var/www/html
      - wtsl-volume:/var/www/wtsl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm
    networks:
      - default

  mysql:
    image: canfone/mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - default

volumes:
    html-volume:
    wtsl-volume:
